version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    image: ${APP_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    depends_on:
      db:
        condition: service_healthy
    tty: true
    command: bin/rails s -b 0.0.0.0
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - VITE_RUBY_HOST=vite
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
      - node_modules_data:/home/nonroot/app/node_modules
    restart: always
  vite:
    image: ${APP_IMAGE_NAME}
    depends_on:
      db:
        condition: service_healthy
    command: bin/vite dev
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DEBUG='*vite*'
      - VITE_RUBY_HOST=0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
      - node_modules_data:/home/nonroot/app/node_modules
    restart: always
  guard:
    image: ${APP_IMAGE_NAME}
    depends_on:
      db:
        condition: service_healthy
      chrome:
        condition: service_healthy
    tty: true
    stdin_open: true
    command: bin/guard
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SELENIUM_DRIVER_URL=http://chrome:4444/
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
      - node_modules_data:/home/nonroot/app/node_modules
    restart: always
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
    restart: always
    healthcheck:
      test: "curl -f http://localhost:4444/status || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5

#  mailcatcher:
#    image: 'schickling/mailcatcher'
#    ports:
#      - "1025:1025"
#      - "1080:1080"
#  redis:
#    image: redis
#    ports:
#      - '6379:6379'
#
volumes:
  postgres_data:
  bundle_data:
  node_modules_data:

