version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: ${APP_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    tty: true
    depends_on:
      - vite
      - db
    command: bin/rails s -b 0.0.0.0
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - VITE_RUBY_HOST=vite
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
  vite:
    image: ${APP_IMAGE_NAME}
    command: bin/vite dev
    environment:
      - DEBUG='*vite*'
      - VITE_RUBY_HOST=0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
  guard:
    image: ${APP_IMAGE_NAME}
    tty: true
    stdin_open: true
    command: bin/guard
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SELENIUM_DRIVER_URL=http://chrome:4444/
    volumes:
      - .:/home/nonroot/app
      - bundle_data:/usr/local/bundle
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
        

#  mailcatcher:
#    image: 'schickling/mailcatcher'
#    ports:
#      - "1025:1025"
#      - "1080:1080"
#  redis:
#    image: redis
#    ports:
#      - '6379:6379'
#
volumes:
  postgres_data:
  bundle_data:

