---
:verbose: false
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low
# :schedule:
#   sample:
#     every: '1m'
#     class: SampleJob
# 
